apiVersion: v1
kind: Service
metadata:
  name: operator
  labels:
    app: operator
spec:
  type: ClusterIP
  selector:
    app: operator
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
