// Public Operator SDK entrypoint. Re-export client namespaces, event helpers,
// transport, and stable SDK types from focused modules.
export {
  Agent,
  AgentsNamespace,
  ApprovalsNamespace,
  ArtifactsNamespace,
  EnvironmentsNamespace,
  ModelsNamespace,
  Operator,
  Run,
  RunsNamespace,
  Session,
  SessionsNamespace,
  TasksNamespace,
  ToolsNamespace,
  type OperatorOptions,
} from "./client.js";
export { EventHub, isGatewayEvent } from "./event-hub.js";
export { normalizeGatewayEvent } from "./normalize.js";
export { GatewayClientTransport, isConnectableTransport } from "./transport.js";
export type {
  AgentsCreateParams,
  AgentsDeleteParams,
  AgentsUpdateParams,
  AgentRunParams,
  ApprovalDecisionParams,
  ApprovalMode,
  ArtifactQuery,
  ArtifactSummary,
  ArtifactsDownloadResult,
  ArtifactsGetResult,
  ArtifactsListResult,
  ConnectableOperatorTransport,
  EnvironmentCreateParams,
  EnvironmentSelection,
  EnvironmentSummary,
  EnvironmentsListResult,
  GatewayEvent,
  GatewayRequestOptions,
  JsonObject,
  OperatorEvent,
  OperatorEventType,
  OperatorTransport,
  RunCreateParams,
  RunResult,
  RunStatus,
  RuntimeSelection,
  SDKError,
  SDKMessage,
  SessionCreateParams,
  SessionSendParams,
  SessionTarget,
  TaskStatus,
  TaskSummary,
  TasksCancelResult,
  TasksGetResult,
  TasksListParams,
  TasksListResult,
  ToolsEffectiveParams,
  ToolInvokeParams,
  ToolInvokeResult,
  WorkspaceSelection,
  WorkerEnvironmentMetadata,
  WorkerEnvironmentState,
  WorkerTunnelStatus,
} from "./types.js";
